### ISSUE TITLE
instructions unclear

### ISSUE THREAD

**Issue by tobit6795** [ReneTode/fully-kiosk-app#1]
Hi, could you please give a little bit more explanation on how to configure this.
Do i need to change anything on my Fully Kiosk device except enabling mqtt(plus adding broker and credentials)?
where do i get the client port? when i check my host with telnet on 1883, it refuses. Or do you mean with client{id,password,..} the broker itself? 

Edit: so for me it looks like it expects the broker, this is what i get at the moment

```
2022-03-09 13:39:29.297934 WARNING fully_mqtt: ------------------------------------------------------------
2022-03-09 13:39:29.298088 WARNING fully_mqtt: Unexpected error running initialize() for fully_mqtt
2022-03-09 13:39:29.298205 WARNING fully_mqtt: ------------------------------------------------------------
2022-03-09 13:39:29.299067 WARNING fully_mqtt: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 150, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 290, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/fully_mqtt.py", line 9, in initialize
    for id, device in self.args["devices"].items():
```

Edit2:  ok, i think i configured it properly, but i dont see any new sensor
btw, is this app only exposing sensors? if yes, then i think  the description "an app to control fully kiosk from appdaemon " is invalid

**Comment by ReneTode** [comment]
the new sensors are inside a group, so youll need to look for a group in HA.

if you look at the code then you also can control the tablet.
but for that youll need to create input_numbers for volume and brightness, and input_booleans for reload, restart and doorbell.
if you create those in HA (not like i do from AD) then most likely the code needs to be changed on some parts.
